### ISSUE TITLE
Submenu disappears when i don't hover the menu link.

### ISSUE THREAD

**Issue by kasperaamodt** [frontity-demos/demo-submenus#4]
Hi, 
Thank you for the code! 

I just have one problem, i have implemented it on the site https://pcvalmenning.vercel.app, and when i hover the menu, the submenu appears. But when i drag my pointer down towards the submenu, it disappears. Do you know how to fix this? I can add my site to a repository if that is necessary.

**Comment by ClaireCaudwell** [comment]
@kasperaamodt I'm having this same issue. Did you manage to figure it out or get help?

**Comment by kasperaamodt** [comment]
@ClaireCaudwell I ended up making my own, let me see if I still have a copy of it!

**Comment by kasperaamodt** [comment]
Here is the [nav menu component](https://github.com/aamodtgroup/hostwp/blob/main/packages/agtech/src/components/header/nav.js) for [HostWP](https://hostwp.no/), a site that I made. The first menu point has a submenu. The component also fetches the menu from WP.

**Comment by ClaireCaudwell** [comment]
@kasperaamodt Ok thank you very much! I will have a look.
